version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@patternfly/react-core"
      - dependency-name: "@redhat-cloud-services/*"
        dependency-type: direct
    open-pull-requests-limit: 2
    commit-message:
      prefix: "build: "
