name: Release workflow
on:
  workflow_run:
    workflows: [lint-test]
    branches: [main, ci-beta, qa-beta, stage-beta, prod-stable, ci-stable, qa-stable, stage-stable, prod-stable]
    types:
      - completed
jobs:
  pull-scripts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ${{ github.workspace }}/scripts
      - name: Pull release file
        run: curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/release.sh > ${{ github.workspace }}/scripts/release.sh
      - run: chmod +x "${{ github.workspace }}/scripts/release.sh"
      - name: Pull nginx conf file
        run: curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/nginx_conf_gen.sh > ${{ github.workspace }}/scripts/nginx_conf_gen.sh
      - run: chmod +x "${{ github.workspace }}/scripts/nginx_conf_gen.sh"
      - name: Pull quay push file
        run: curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/quay_push.sh > ${{ github.workspace }}/scripts/quay_push.sh
      - run: chmod +x "${{ github.workspace }}/scripts/quay_push.sh"
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/scripts/*
          key: ${{ github.sha }}-scripts
  pull-jenkins:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ${{ github.workspace }}/.travis
      - name: Pull the file
        run: curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/Jenkinsfile > ${{ github.workspace }}/.travis/58231b16fdee45a03a4ee3cf94a9f2c3
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.travis/58231b16fdee45a03a4ee3cf94a9f2c3
          key: ${{ github.sha }}-travis
  set-ssh:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            echo "Host github.com
              HostName github.com
              User git
              AddKeysToAgent yes
              IdentityFile /home/runner/.ssh/github_actions" >> /home/runner/.ssh/config
      - uses: actions/cache@v2
        with:
          path: /home/runner/.ssh/*
          key: ${{ github.sha }}-ssh
  Release-to-build:
    needs: [pull-scripts, pull-jenkins, set-ssh]
    runs-on: ubuntu-latest
    env:
      COMMIT_AUTHOR_USERNAME: GitHub actions
      COMMIT_AUTHOR_EMAIL: actions@github.com
    steps:
      - uses: actions/checkout@v2
      - name: Set env variables
        run: |
          echo "TRAVIS_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "TRAVIS_BUILD_NUMBER=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo ${{ github.event.head_commit.message }}
          echo "TRAVIS_COMMIT_MESSAGE=`git log -1 --pretty=format:"%s"`" >> $GITHUB_ENV
          echo "REPO=`node -e 'console.log(require("${{ github.workspace }}/package.json").insights.buildrepo)'`" >> $GITHUB_ENV
      - run: git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
      - uses: actions/cache@v2
        with:
          path: /home/runner/.ssh/*
          key: ${{ github.sha }}-ssh
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/scripts/*
          key: ${{ github.sha }}-scripts
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.travis/58231b16fdee45a03a4ee3cf94a9f2c3
          key: ${{ github.sha }}-travis
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}
      - name: Run the deploy
        run: ${{ github.workspace }}/custom_release.sh
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}-released
